---
title: "subset_samples"
output: html_document
date: "2023-04-26"
---

## Description
Code to extract subset of burned and unburned polygons for proof-of-concept.

## Set up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### Load packages
library(tidyverse)
library(sf)
library(lubridate)
```

## Subset samples
```{r}
### Open data, add column for type of polygon 
burned_polygons <- st_read("C:/Users/kjsie/OneDrive/Documents/recovery-group/Buffered_fire/recovery.shp") %>%
  mutate(burned_status = "burned")
unburned_polygons <- st_read("C:/Users/kjsie/OneDrive/Documents/recovery-group/Buffered_fire/unburned.shp") %>%
  mutate(burned_status = "unburned")

### Randomly sample 10 burned polygons
burned_sub <- burned_polygons %>%
  sample_n(10)

### Get the corresponding unburned polygons
unburned_sub <- unburned_polygons %>%
  filter(Event_ID %in% burned_sub$Event_ID)

### Combine into single sf
all_sub <- rbind(burned_sub,
                 unburned_sub)

### Extract dates
all_sub <- all_sub %>%
  mutate(year_fire = year(Ig_Date),
         month_fire = month(Ig_Date),
         day_fire = day(Ig_Date))

### Add unique ID
all_sub <- all_sub %>%
  mutate(unique_id = paste0(burned_status, "_",
                            Event_ID))
```

## Make sample points
```{r}
### Make sample grid
point_grid <- map(all_sub$unique_id, function(x) {
  
  ### subset to individual polygon
  poly <- all_sub %>% filter(unique_id == x)
  
  ### make sample points for the polygon
  poly_samples <- poly %>%
    ### Make samples (cellsize is where I'm defining the grid)
    st_make_grid(cellsize = c(500, 500), what = "centers") %>%
    
    ### Convert to sf
    st_sf()  %>%
    
    ### Add identifiers
    mutate(unique_id = x,
           lon = st_coordinates(.)[,1],
           lat = st_coordinates(.)[,2])
  
  ### Intersect with polygon to drop points outside boundary
  poly_samples <- st_intersection(poly_samples, poly)
  
  return(poly_samples)
})

### Combine
sample_grid <- do.call(rbind, point_grid)

### Drop extra col
sample_grid <- sample_grid %>%
  dplyr::select(-unique_id.1)
```

### Write out data
```{r}
st_write(all_sub,
         "C:/Users/kjsie/OneDrive/Documents/recovery-group/Buffered_fire/subset_polys.shp")
st_write(sample_grid,
         "C:/Users/kjsie/OneDrive/Documents/recovery-group/Buffered_fire/subset_points.shp")
```

